import { createSlice } from "@reduxjs/toolkit"

// declare initialState
const initialState= {
    value: 'profile'
}

//createSlice is used to make a slice
export const selectDashboardSlice = createSlice({
    name: 'selectDashboard',
    initialState,
    reducers:{
        profile:(state) => {state.value = "profile"},
        order:(state) =>{state.value = "order"},
        returns:(state) =>{state.value = "return"}
    }
})

// export are auto-generated by redux
// Action creators are generated for each case reducer function
export const { profile, order, returns } = selectDashboardSlice.actions;
export default selectDashboardSlice.reducer;